apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fullname" . }}-config-map"
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  nginxMainConfig: |-
{{ tpl (.Files.Get "configs/nginx.conf") . | indent 4 }}
  nginxServerConfig: |-
{{ tpl (.Files.Get "configs/default.conf.template") . | indent 4 }}
